### ISSUE TITLE
Help! @charlie-quinn

### ISSUE THREAD

**Issue by briannabeauchamp** [briannabeauchamp/fastness-fixer#1]
Hey so I can't quite figure out how to get the word snail back up next to the svg of a snail at top of the page. Possibly modulifier issue? @charlie-quinn

**Comment by charlie-quinn** [comment]
It looks like you removed too many classes in your `modules.css` file!
- [ ] include *positioning* classes when revising [Modulifier's settings](https://modulifier.web-dev.tools/)

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️Reminder: please close this issue once it has been resolved.

**Comment by charlie-quinn** [comment]
⚠️Reminder: please close this issue once it has been resolved.
